name: On Pull Request
run-name: ${{ github.actor }} triggered ${{ github.workflow }} for ${{ github.event_name }} ${{ github.event.pull_request.number }}
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  print-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print PR number
        run: echo "PR number is ${{ github.event.pull_request.number }}"
  run-tests:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Test
        run: |
          source .venv/bin/activate
          tox
  on_merge:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: [print-pr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print PR number
        run: echo "PR number ${{ github.event.pull_request.number }} is merged"
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run build
        run: |
          source .venv/bin/activate
          poetry build
