name: On PR - Run tests
run-name: ${{ github.actor }} triggered ${{ github.workflow }} for ${{ github.event_name }} ${{ github.event.pull_request.number }}
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  print-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR number
        run: echo "PR number is ${{ github.event.pull_request.number }}"
  run-tests:
    uses: ./.github/workflows/template-python-tox-test.yaml
  on_merge:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: [print-pr, run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Print PR number
        run: echo "PR number ${{ github.event.pull_request.number }} is merged"
