name: On PR - Run tests
on: [workflow_call]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup.yaml
      - name: Run build
        run: |
          source .venv/bin/activate
          poetry build
